version: '3'

services:
  # Frontend - Next.js application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - nick-network

  # Backend API - Node.js/Express
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/nick_agent
      - JWT_SECRET=local_development_secret
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - AGENT_CORE_HOST=agent-core
      - AGENT_CORE_PORT=50051
      - LOG_LEVEL=INFO
    depends_on:
      - mongo
      - agent-core
    networks:
      - nick-network

  # Agent Core service - Python/gRPC
  agent-core:
    build:
      context: ./agent_core
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - ./agent_core:/app
      - ./task_modules:/app/task_modules
    environment:
      - AGENT_CORE_PORT=50051
      - ABACUSAI_API_KEY=${ABACUSAI_API_KEY}
      - BACKEND_HOST=backend
      - BACKEND_PORT=3001
    networks:
      - nick-network

  # MongoDB database
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - nick-network

networks:
  nick-network:
    driver: bridge

volumes:
  mongo-data:
