version: '3'

services:
  # Frontend - Next.js application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - nick-network

  # Backend API - Node.js/Express
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/nick_agent
      - JWT_SECRET=local_development_secret
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - mongo
    networks:
      - nick-network

  # MongoDB database
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - nick-network

networks:
  nick-network:
    driver: bridge

volumes:
  mongo-data:
