services:
  - type: web
    name: nick-the-great
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: JWT_SECRET
        value: 279ce94da80914df09784273c47c7cfcca393525b89925f4caaf999f1e3b62f5
      - key: GEMINI_API_KEY
        value: AIzaSyDvW-t7LRH3XtvKfcC8zAtLBYpEhaA4z_k
      - key: MONGODB_URI
        value: mongodb+srv://nick_the_great:hOdM4hyeTswFQjQF@cluster0.rzjjbtu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: AGENT_CORE_HOST
        value: localhost
      - key: AGENT_CORE_PORT
        value: "50052"
